export const mineBg1 = 'https://pic.ocexam.cn/white-headphone-1037992.jpg'
export const loading = 'https://pic.ocexam.cn/Pulse-1.2s-257px.gif'
export const logo = 'https://pic.ocexam.cn/%E5%B7%A5%E5%9D%8A2.png'


export const raceShowBg = 'https://assets2.iranshao.com/191210Race_details_bg.jpg'
export const addPhone = 'https://assets2.iranshao.com/20191217add_photo.png'
// export const loginDefaultAvatar = 'https://assets2.iranshao.com/20191217loginDefaultAvatar.png'
export const loginBackground = 'https://assets2.iranshao.com/20191217loginBackground.png'
export const imgGrayTriangle = 'https://assets2.iranshao.com/20191217gray-triangle.svg'
export const wechatIcon = 'https://assets2.iranshao.com/191213Wechat_icons.png'
export const iranshaoIcon = 'https://assets2.iranshao.com/191213iranshao_icons.png'
export const iranshaoLogo = 'https://assets2.iranshao.com/191213iranshao_logo.png'
export const iranshaoSlogan = 'https://assets2.iranshao.com/191213iranshao_slogan.png'
export const loginDefaultAvatar = 'https://pic.ocexam.cn/20191217loginDefaultAvatar.png'
